#[derive(Model, Copy, Drop, Serde)]
struct Adventurer {
    #[key]
    last_action_block: u16,
    health: u16,
    xp: u16,
    gold: u16,
    weapon_id: u8,
    weapon_xp: u16,
    weapon_metadata: u8,
    chest_id: u8,
    chest_xp: u16,
    chest_metadata: u8,
    head_id: u8,
    head_xp: u16,
    head_metadata: u8,
    waist_id: u8,
    waist_xp: u16,
    waist_metadata: u8,
    foot_id: u8,
    foot_xp: u16,
    foot_metadata: u8,
    hand_id: u8,
    hand_xp: u16,
    hand_metadata: u8,
    neck_id: u8,
    neck_xp: u16,
    neck_metadata: u8,
    ring_id: u8,
    ring_xp: u16,
    ring_metadata: u8,
    beast_health: u16,
    stat_points_available: u8,
    actions_per_block: u8,
    mutated: bool,
    strength: u8,
    dexterity: u8,
    vitality: u8,
}